name: tekartik_firebase_storage_node
description: Firebase storage node
version: 0.4.2
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  collection: '>=1.14.10'
  js: any
  sembast: '>=1.7.0'
  uuid: '>=1.0.0'
  tekartik_firebase_node:
    git:
      url: git://github.com/tekartik/firebase_node.dart
      path: firebase_node
      ref: null_safety
    version: '>=0.4.0'
  tekartik_firebase_storage:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: null_safety
    version: '>=0.4.0'
  tekartik_firebase_storage_fs:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage_fs
      ref: null_safety
    version: '>=0.4.2'
  tekartik_app_node_utils:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: null_safety
    version: '>=0.1.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.12.0-dev.1'
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: null_safety
  tekartik_firebase_storage_test:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage_test
      ref: null_safety
    version: '>=0.4.0'
  process_run: '>=0.10.2'

  # Node needed dev dependencies
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: null_safety
    version: '>=0.1.0'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: git://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: null_safety
dependency_overrides:
  tekartik_firebase_node:
    path: ../firebase_node
  # Temp
  # tekartik_app_node_build:
  #   path: ../../app_node_utils.dart/app_build
