name: tekartik_firebase_storage_node
description: Firebase storage node
version: 0.4.2+1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.7.0

dependencies:
  path: ">=1.9.0"
  collection: ">=1.18.0"
  sembast: ">=3.7.4+3"
  uuid: '>=1.0.0'
  tekartik_firebase_node:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: firebase_node
      ref: dart3a
    version: '>=0.4.0'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart3a
    version: '>=0.4.0'
  tekartik_firebase_storage_fs:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_fs
      ref: dart3a
    version: '>=0.4.2'
  tekartik_app_node_utils:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart3a
    version: '>=0.1.0'
  tekartik_js_utils_interop:
    git:
      url: https://github.com/tekartik/js_utils.dart
      path: js_utils_interop
      ref: dart3a
    version: '>=0.1.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase
  tekartik_firebase_storage_test:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      ref: dart3a
      path: storage_test
  tekartik_core_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      ref: dart3a
      path: core_node
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.0+2"
  process_run: ">=1.2.1+1"

  # Node needed dev dependencies
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'
  # needed node dependencies
  build_runner: ">=2.4.13"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      ref: dart3a
      path: platform_node

resolution: workspace
  # Temp
  # tekartik_app_node_build:
  #   path: ../../app_node_utils.dart/app_build
