name: tekartik_firebase_node
description: Firebase server node
version: 0.7.5
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: '>=1.14.10'
  js: any
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: null_safety
    version: '>=0.7.3'
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: null_safety
    version: '>=0.6.0'
  tekartik_platform_node:
    git:
      url: git://github.com/tekartik/common_node.dart
      path: platform_node
      ref: null_safety
    version: '>=0.2.1'
  # firebase_admin_interop: ">=1.1.0"
  firebase_admin_interop:
    git:
      url: git://github.com/tekartikdev/firebase-admin-interop
      ref: null_safety

dev_dependencies:
  test: ">=1.2.0"
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: null_safety
  tekartik_firebase_test:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_test
      ref: null_safety
      version: '>=0.7.3'
  process_run:
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: git://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: null_safety

dependency_overrides:
  # tekartik_firebase:
  #  path: ../firebase
  # tekartik_firebase_local:
  #  path: ../firebase_local
  # quiver_hashcode: '>=1.0.0'
#  firebase_admin_interop:
#    git: git://github.com/asaarnak/firebase-admin-interop