name: tekartik_firebase_firestore_node
description: Firebase firestore server node
version: 0.10.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  collection: ">=1.18.0"
  uuid: '>=1.0.0'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
    version: '>=1.1.1'
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
    version: '>=0.8.2'
  tekartik_firebase_node:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: firebase_node
    version: '>=0.8.0'

dev_dependencies:
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
  tekartik_firebase_firestore_test:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_test
    version: '>=0.8.0'
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  # needed node dependencies
  build_runner: ">=2.4.13"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node

  # temp test
_temp_dependency_overrides:
  tekartik_firebase_firestore:
    path: ../../firebase_firestore.dart/firestore
  tekartik_firebase_firestore_test:
    path: ../../firebase_firestore.dart/firestore_test
resolution: workspace

