name: tekartik_firebase_firestore_node
description: Firebase firestore server node
version: 0.8.2
publish_to: none

environment:
  sdk: '>=2.9.0-0 <3.0.0'

dependencies:
  collection: '>=1.14.10'
  js: any
  uuid: '>=1.0.0'
  tekartik_firebase_firestore:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: null_safety
    version: '>=0.8.0'
  tekartik_firebase_firestore_sembast:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: null_safety
    version: '>=0.8.2'
  tekartik_firebase_node:
    git:
      url: git://github.com/tekartik/firebase_node.dart
      path: firebase_node
      ref: null_safety
    version: '>=0.6.1'

dev_dependencies:
  tekartik_firebase_firestore_test:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore_test
      ref: null_safety
    version: '>=0.8.0'
  test: ">=1.2.0"
  dev_test: '>=0.12.0-dev.1'
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: null_safety
  process_run: '>=0.10.2'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: git://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: null_safety

dependency_overrides:
  tekartik_firebase_node:
    path: ../firebase_node
