name: tekartik_firebase_auth_node
description: Firebase auth server node
version: 0.9.1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  collection: '>=1.14.10'
  uuid: '>=1.0.0'
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart3a
    version: '>=0.9.0'
  tekartik_firebase_auth_local:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_local
      ref: dart3a
    version: '>=0.3.8'
  tekartik_firebase_node:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: firebase_node
      ref: dart3a
    version: '>=0.4.0+0'
  # firebase_functions_interop: ">=1.0.0-dev.11.0"
  # firebase_admin_interop: ">=1.1.0"

dev_dependencies:
  test: ">=1.2.0"
  dev_build: '>=0.12.0-dev.1'
  grinder: any
  build_test: ">=0.10.3"
  process_run: '>=0.10.0+1'
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'
  tekartik_firebase_auth_test:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_test
      ref: dart3a
    version: '>=0.4.0+0'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

dependency_overrides:
  tekartik_firebase_node:
    path: ../firebase_node
