name: _
publish_to: none
environment:
  sdk: ^3.12.0
workspace:
  - auth_node
  - firebase_node
  - firebase_node_test
  - firestore_node
  - functions_node
  - pubsub_node
  - repo_support
  - repo_support/workflow_ci_firebase_test
  - repo_support/workflow_ci_firestore_test
  - repo_support/workflow_ci_storage_test
  - repo_support/workflow_ci_auth_test
  - storage_node
  - firebase_emulator
