name: tekartik_pubsub_node
description: Pubsub node client
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  js: '>=0.6.1+1'
  meta: '>=1.1.8'
  node_interop:
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      path: js_utils
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_app_node_utils:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart2_3
    version: '>=0.1.0'
dev_dependencies:
  process_run:
  test: '>=1.14.4'
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2_3
    version: '>=0.1.0'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3