name: tekartik_pubsub_node
description: Pubsub node client
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  meta: ">=1.15.0"
  tekartik_app_node_utils:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart3a
    version: '>=0.1.0'
  tekartik_core_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      ref: dart3a
      path: core_node
  tekartik_js_utils_interop:
    git:
      url: https://github.com/tekartik/js_utils.dart
      ref: dart3a
      path: js_utils_interop
dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'
  # needed node dependencies
  build_runner: ">=2.4.13"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
resolution: workspace
