targets:
  $default:
    sources:
      - $package$
      - lib/**
      - test/**
      - node/**
      - bin/**
      - example/**
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - bin/**
          - example/**
        options:
          compiler: dart2js

          # List any dart2js specific args here, or omit it.
          # dart2js_args:
          # - --checked