name: tekartik_firebase_emulator
description: Firebase emulator helper
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  dev_build: ">=1.1.8+2"
  tekartik_common_utils:
    git: https://github.com/tekartik/common_utils.dart
  meta: ">=1.18.0"
  path: ">=1.9.1"
  cv: ">=1.1.11"
  http:
dev_dependencies:
  lints: ">=6.1.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
  test: ">=1.31.0"

resolution: workspace
