name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'

dependency_overrides:
resolution: workspace
  # Temp
  # tekartik_app_node_build:
  #  path: ../../app_node_utils.dart/app_build
